### PR TITLE
defined typeDefs and resolvers for graphQL, working, but may need to …

### PR DESCRIPTION
**Pull request by Proto133**
…revisit, JWT working

### CODE REVIEW

**Review by GPLOTKE — APPROVED** [review]
Nice work

**Review by Ryan1992186 — APPROVED** [review]
Lookin good!

**Review by GPLOTKE — APPROVED** [review]
nice work

**Review by GPLOTKE — APPROVED** [review]
again

**Review by GPLOTKE — COMMENTED** [review]
nice work

**Review by GPLOTKE — APPROVED** [review]

**Pull request merged**
